"""added user task and project task relationships

Revision ID: cfedd8c6f954
Revises: ed66bd3bf9bc
Create Date: 2026-06-11 14:37:20.718389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfedd8c6f954'
down_revision: Union[str, Sequence[str], None] = 'ed66bd3bf9bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
