"""added user task and project task relationship

Revision ID: ed66bd3bf9bc
Revises: 6e806d6e93bf
Create Date: 2026-06-11 14:34:11.066174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed66bd3bf9bc'
down_revision: Union[str, Sequence[str], None] = '6e806d6e93bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('memberships', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('memberships', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('memberships', 'id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('memberships', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('memberships', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('memberships', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
